language: python

before_install:
 - sudo apt-get update
 - wget http://repo.continuum.io/miniconda/Miniconda3-2.0.0-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/anaconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis and
  # are not specific to using Miniconda
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - conda install -c menpo opencv3=3.2.0

install:
  - "pip install --pre -r requirements.txt"

python:
  - "3.6"

script:
  - python main.py
