language: python

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
 - ./build.sh

install:
  - "pip install --pre -r requirements.txt"

python:
  - "3.6"

script:
  - python main.py
